import type { Metadata } from "next";
import './globals.css';  // Make sure this path is correct
import Footer from "@/components/Footer";

// Remove the localFont imports for now to simplify the setup
// We'll add them back once the basic build works

export const metadata: Metadata = {
  title: "MyPorfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}